# Generated by Django 4.2.5 on 2023-09-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_end_date_task_start_date_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата начала'),
        ),
    ]
